name: release

on:
  push:
    tags:
      - 'v*' # Push events for tags matching v*, e.g. v1.0, v20.15.10

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # git history won't be fetched without this option

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Generate Release Notes
        run: npm run changelog-release

      - name: Parse Release Notes
        id: parse
        run: |
          NOTES=$(cat RELEASE.md)
          NOTES="${NOTES//'%'/'%25'}"
          NOTES="${NOTES//$'\n'/'%0A'}"
          echo "::set-output name=notes::$NOTES"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.parse.outputs.notes }}
          draft: true
          prerelease: false
